// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mexicoDestinos.Contexts;

namespace mexicoDestinos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("mexicoDestinos.Models.Airport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AirportName")
                        .HasMaxLength(150);

                    b.Property<string>("IATA")
                        .HasMaxLength(4);

                    b.HasKey("Id");

                    b.ToTable("Airports");
                });

            modelBuilder.Entity("mexicoDestinos.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryName")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("mexicoDestinos.Models.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountryId");

                    b.Property<string>("DestinationName")
                        .HasMaxLength(80);

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("mexicoDestinos.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DestinationId");

                    b.Property<string>("HotelName")
                        .HasMaxLength(150);

                    b.Property<string>("ZoneCode");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("ZoneCode");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("mexicoDestinos.Models.Shuttle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("MarkUp");

                    b.Property<decimal>("NetRate");

                    b.Property<string>("ShuttleCode")
                        .HasMaxLength(1);

                    b.Property<int>("ShuttleTextId");

                    b.Property<decimal>("Tax");

                    b.Property<string>("ZoneCode");

                    b.HasKey("Id");

                    b.HasIndex("ShuttleTextId");

                    b.HasIndex("ZoneCode");

                    b.ToTable("Shuttles");
                });

            modelBuilder.Entity("mexicoDestinos.Models.ShuttleText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Language")
                        .HasMaxLength(3);

                    b.Property<string>("ShuttleContent")
                        .HasMaxLength(300);

                    b.Property<string>("ShuttleName")
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.ToTable("ShuttleTexts");
                });

            modelBuilder.Entity("mexicoDestinos.Models.Zone", b =>
                {
                    b.Property<string>("ZoneCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10);

                    b.Property<int>("AirportId");

                    b.Property<string>("ZoneName")
                        .HasMaxLength(150);

                    b.HasKey("ZoneCode");

                    b.HasIndex("AirportId");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("mexicoDestinos.Models.Destination", b =>
                {
                    b.HasOne("mexicoDestinos.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("mexicoDestinos.Models.Hotel", b =>
                {
                    b.HasOne("mexicoDestinos.Models.Destination", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("mexicoDestinos.Models.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneCode");
                });

            modelBuilder.Entity("mexicoDestinos.Models.Shuttle", b =>
                {
                    b.HasOne("mexicoDestinos.Models.ShuttleText", "ShuttleText")
                        .WithMany()
                        .HasForeignKey("ShuttleTextId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("mexicoDestinos.Models.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneCode");
                });

            modelBuilder.Entity("mexicoDestinos.Models.Zone", b =>
                {
                    b.HasOne("mexicoDestinos.Models.Airport", "Airport")
                        .WithMany()
                        .HasForeignKey("AirportId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
